### ISSUE TITLE
can't find campaign page

### ISSUE THREAD

**Issue by MichaelLSmith** [MatthieuScarset/wordpress-mailchimp-campaign#1]
I'm trying your plugin out. I was able connect up with my mailchip account with the api key. I imported my two test campaigns. I see them listed as a newsletter custom post type. But when I try to view them as a post, I get the generic "page not found". The url looks fine.

http://michaelsmith.x10host.com/wp/newsletter/second-test-campaign/

Are you still working on this plugin?

**Comment by MatthieuScarset** [comment]
Hi @MichaelLSmith 
Thank you for your comment and for trying this plugin.

Unfortunately, I do not watch this repo.

Please join us on the WordPress support forum:
https://wordpress.org/support/plugin/olalaweb-mailchimp-campaign-manager/

Regarding your issue, it is a known issue actually.
Solution is detailed in the FAQ section.
You should simply have to refresh your permalinks settings :)
