### ISSUE TITLE
Import Campaign seems not to work in v3.1.0

### ISSUE THREAD

**Issue by TalithaCumi** [MatthieuScarset/wordpress-mailchimp-campaign#2]
I tried to import a huge campaign archive (around 130 campaigns) to a self hosted wordpress version 4.7.2 but it seems not to work. API key and user name work for other mailchimp plugins.

I saw that this plugin has been tested with wordpress 4.6. but hoped it would work anyway.

it seems to be stuck at 
>  Talking to the chimp...
> Please wait until all campaigns are imported.
> This may take a while if you have many campaigns in your Mailchimp account.

I can create new campaigns in the archive manager, though. Maybe something changed on the mailchimp API side?

ETA: activated WP_DEBUG_LOG and it throws this after I started import campaign:

PHP Fatal error:  Cannot use object of type WP_Error as array in /var/www/html/wordpress/wp-content/plugins/olalaweb-mailchimp-campaign-manager/class/MailchimpCampaigns.php on line 90

**Comment by Nslaver** [comment]
```
$count = $this->getTotal();
$args = $this->args(array('count'=>$count));
$results = $this->call('campaigns', $args);
$this->campaigns = json_decode( $results->last_call['body'] );
```
I have the exact same problem, the $result variable has this:

MailchimpCampaigns::__set_state(array( 'settings' => array ( 'api_authname' => 'theuser', 'cpt_name' => '', 'api_key' => 'myapikey-dc', 'api_datacentre' => 'dc', 'api_version' => '3.0', 'api_endpoint' => 'https://dc.api.mailchimp.com/3.0', ), 'is_error' => true, 'last_error' => NULL, 'last_call' => WP_Error::__set_state(array( 'errors' => array ( 'http_request_failed' => array ( 0 => 'Operation timed out after 5001 milliseconds with 0 bytes received', ), ), 'error_data' => array ( ), )), 'last_updated' => '2017-06-01 11:26:29', 'data' => NULL, ))

**Comment by sergioleser** [comment]
Mathieu

I´m willing to use mailchimp campaigns on a site so I´m dedicating some time to help improving mailchimp campaigns.

After some investigation I found out the plugin stops functioning when importing around 70 campaign archives. 

In these cases the $args variable returns: 

"args [mailchimpcampaigns.args] object(WP_Error)#7447 (2) { ["errors"]=> array(1) { ["http_request_failed"]=> array(1) { [0]=> string(17) "fsocket timed out" } } ["error_data"]=> array(0) { } }"

Adjusting PHP.ini's default_socket_timeout won't extend much further the number of campaigns exported

I'm running some tests on a workaround and will soon submit you my contribution.

Sérgio Leser

**Comment by MatthieuScarset** [comment]
Hi, thank you for all your comments and debugging. 
I am sorry I am not watching this repository.

Instead, we use the WordPress plugin page and its support thread:
https://wordpress.org/support/plugin/olalaweb-mailchimp-campaign-manager/

Anyway, thanks to your previous comments I think I have found out what breaks the import.
Returned data might be an error in `MailchimpCampaigns` class `fetch()` function.

I'll test this and release a new version soon.
